//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingVisual.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public Cart()
        {
            this.Cart_Details = new HashSet<Cart_Details>();
            this.Orders = new HashSet<Order>();
        }
    
        public int Cart_Id { get; set; }
        public int Customer_ID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Cart_Details> Cart_Details { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
