//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingVisual.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart_Details
    {
        public Cart_Details()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int Cart_Details_Id { get; set; }
        public int Cart_Id { get; set; }
        public int Product_Id { get; set; }
        public Nullable<int> Product_Price { get; set; }
        public int Product_Quantity { get; set; }
        public Nullable<int> Total_Order_Amount { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Product Product { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
