//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingVisual.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int Id { get; set; }
        public string Order_Id { get; set; }
        public Nullable<int> Cart_Details_Id { get; set; }
        public System.DateTime Order_Date { get; set; }
        public string Payment_Mode { get; set; }
    
        public virtual Cart_Details Cart_Details { get; set; }
    }
}
