//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingVisual.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Retailer
    {
        public Retailer()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int Retailer_ID { get; set; }
        public string Retailer_Name { get; set; }
        public string Retailer_ContactNo { get; set; }
        public string Retailer_Address { get; set; }
        public string Retailer_Country { get; set; }
        public string Retailer_State { get; set; }
        public string Retailer_City { get; set; }
        public string Retailer_PostalCode { get; set; }
        public string Retailer_Email { get; set; }
        public string Retailer_Password { get; set; }
        public string Customer_Type { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}
