//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingVisual.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WishList_items
    {
        public int WishList_items_Id { get; set; }
        public Nullable<int> WishList_ID { get; set; }
        public int Product_Id { get; set; }
        public string Product_Image { get; set; }
        public string Product_Desc { get; set; }
        public Nullable<int> Product_Price { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual WishList WishList { get; set; }
    }
}
